site_name: OpenInventory
site_description: Documentation for ZonePlus
site_author: Ben Horton
site_url: https://xnlogical.github.io/OpenInvetory/

repo_name: XnLogicaL/OpenInventory
repo_url: https://github.com/XnLogicaL/OpenInventory
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    #- navigation.instant
    #- navigation.sections
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - lua